[build]
builder = 'DOCKERFILE'
dockerfilePath = './Dockerfile'
watchPatterns = [
    'src/**/*',
    'public/**/*',
    'package.json',
    'railway.toml',
    'Dockerfile',
    'requirements.txt',
]